### PR TITLE
Add-comments

### PR DESCRIPTION
**Pull request by frankspaceye**
Add some comments in the python file.

### CODE REVIEW

**Comment by frankspaceye** [comment]
Is anyone has questions?

**Comment by qs9** [comment]
yes, i have one.

**Comment by frankspaceye** [comment]
What's your question?

**Comment by qs9** [comment]
Good, i get it now.

**Comment by frankspaceye** [comment]
Do you agree now?

**Comment by qs9** [comment]
Let me test.

**Pull request merged**
